---
- name: ensure directory for unpacking exists
  file:
    path: /opt/prometheus
    state: directory

- name: Fetch and unarchive prometheus
  unarchive:
    src: 'https://github.com/prometheus/prometheus/releases/download/v2.6.0/prometheus-2.6.0.linux-armv7.tar.gz'
    dest: '/opt/prometheus'
    extra_opts: [--strip-components=1]
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"


- name: Configure supervisor for prometheus
  blockinfile:
    path: /etc/supervisor/conf.d/prometheus.conf
    create: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    block: |
      [program:prometheus]
      command=/opt/prometheus/prometheus
      directory=/opt/prometheus
      autostart=true
      autorestart=true
      startretries=3
      stderr_logfile=/var/log/prometheus.err.log
      stdout_logfile=/var/log/prometheus.out.log
      user={{ ansible_user_id }}


- name: Configure prometheus yaml config
  template:
    src: yaml.j2
    dest: /opt/prometheus/prometheus.yml
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

- name: Read in supervisor config
  command: supervisorctl reread

- name: Update supervisor config
  command: supervisorctl update
